include:
- file: /r4.2/gitlab-base.yml
  project: qubesos/qubes-continuous-integration
- file: /r4.2/gitlab-host.yml
  project: qubesos/qubes-continuous-integration
- file: /r4.2/gitlab-vm.yml
  project: qubesos/qubes-continuous-integration
- file: /r4.3/gitlab-base.yml
  project: qubesos/qubes-continuous-integration
- file: /r4.3/gitlab-host.yml
  project: qubesos/qubes-continuous-integration
- file: /r4.3/gitlab-vm.yml
  project: qubesos/qubes-continuous-integration

checks:tests:
  stage: checks
  variables:
    PYTEST_ADDOPTS: "--color=yes"
  before_script: &before-script
    - "PATH=$PATH:$HOME/.local/bin"
    - sudo dnf install -y python3-pytest python3-coverage python3-pip
    - pip3 install --quiet -r ci/requirements.txt
  script:
    - ./run-tests.sh
  after_script:
    - "PATH=$PATH:$HOME/.local/bin"
    - ci/codecov-wrapper

checks:pylint:
  before_script:
  - sudo dnf install -y python3-mypy python3-pip
  - pip3 install --quiet -r ci/requirements.txt
  - mypy --install-types --non-interactive
  script:
  - python3 -m pylint --rcfile=.pylintrc qubesctap
  - mypy qubesctap
  stage: checks
